######################################################################
# Automatically generated by qmake (3.1) Fri Jul 1 10:26:25 2022
######################################################################

TEMPLATE = app
TARGET = deformation
INCLUDEPATH += .

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

INCLUDEPATH  +=  algorithm/
INCLUDEPATH  +=  algorithm/Eigen/
INCLUDEPATH += /usr/local/include/eigen3/Eigen
INCLUDEPATH += /usr/local/include/opencv4
INCLUDEPATH += /usr/local/cuda/include

DEPENDPATH  += /usr/local/cuda/lib64
DEPENDPATH  += /usr/lib64
DEPENDPATH  += /usr/local/lib
DEPENDPATH  += /usr/local/cuda//targets/x86_64-linux/lib64
DEPENDPATH  += cudart

# Input
HEADERS += algorithm/MeshTransfer.h \
           algorithm/ParameterConfig.h \
           algorithm/Renderable/bmesh.h \
           algorithm/Renderable/bmesh_private.h \
           algorithm/Renderable/ObjMesh.h \
           algorithm/Renderable/Renderable.h \
           algorithm/Eigen/src/Cholesky/LDLT.h \
           algorithm/Eigen/src/Cholesky/LLT.h \
           algorithm/Eigen/src/Cholesky/LLT_LAPACKE.h \
           algorithm/Eigen/src/CholmodSupport/CholmodSupport.h \
           algorithm/Eigen/src/Core/ArithmeticSequence.h \
           algorithm/Eigen/src/Core/Array.h \
           algorithm/Eigen/src/Core/ArrayBase.h \
           algorithm/Eigen/src/Core/ArrayWrapper.h \
           algorithm/Eigen/src/Core/Assign.h \
           algorithm/Eigen/src/Core/Assign_MKL.h \
           algorithm/Eigen/src/Core/AssignEvaluator.h \
           algorithm/Eigen/src/Core/BandMatrix.h \
           algorithm/Eigen/src/Core/Block.h \
           algorithm/Eigen/src/Core/BooleanRedux.h \
           algorithm/Eigen/src/Core/CommaInitializer.h \
           algorithm/Eigen/src/Core/ConditionEstimator.h \
           algorithm/Eigen/src/Core/CoreEvaluators.h \
           algorithm/Eigen/src/Core/CoreIterators.h \
           algorithm/Eigen/src/Core/CwiseBinaryOp.h \
           algorithm/Eigen/src/Core/CwiseNullaryOp.h \
           algorithm/Eigen/src/Core/CwiseTernaryOp.h \
           algorithm/Eigen/src/Core/CwiseUnaryOp.h \
           algorithm/Eigen/src/Core/CwiseUnaryView.h \
           algorithm/Eigen/src/Core/DenseBase.h \
           algorithm/Eigen/src/Core/DenseCoeffsBase.h \
           algorithm/Eigen/src/Core/DenseStorage.h \
           algorithm/Eigen/src/Core/Diagonal.h \
           algorithm/Eigen/src/Core/DiagonalMatrix.h \
           algorithm/Eigen/src/Core/DiagonalProduct.h \
           algorithm/Eigen/src/Core/Dot.h \
           algorithm/Eigen/src/Core/EigenBase.h \
           algorithm/Eigen/src/Core/ForceAlignedAccess.h \
           algorithm/Eigen/src/Core/Fuzzy.h \
           algorithm/Eigen/src/Core/GeneralProduct.h \
           algorithm/Eigen/src/Core/GenericPacketMath.h \
           algorithm/Eigen/src/Core/GlobalFunctions.h \
           algorithm/Eigen/src/Core/IndexedView.h \
           algorithm/Eigen/src/Core/Inverse.h \
           algorithm/Eigen/src/Core/IO.h \
           algorithm/Eigen/src/Core/Map.h \
           algorithm/Eigen/src/Core/MapBase.h \
           algorithm/Eigen/src/Core/MathFunctions.h \
           algorithm/Eigen/src/Core/MathFunctionsImpl.h \
           algorithm/Eigen/src/Core/Matrix.h \
           algorithm/Eigen/src/Core/MatrixBase.h \
           algorithm/Eigen/src/Core/NestByValue.h \
           algorithm/Eigen/src/Core/NoAlias.h \
           algorithm/Eigen/src/Core/NumTraits.h \
           algorithm/Eigen/src/Core/PartialReduxEvaluator.h \
           algorithm/Eigen/src/Core/PermutationMatrix.h \
           algorithm/Eigen/src/Core/PlainObjectBase.h \
           algorithm/Eigen/src/Core/Product.h \
           algorithm/Eigen/src/Core/ProductEvaluators.h \
           algorithm/Eigen/src/Core/Random.h \
           algorithm/Eigen/src/Core/Redux.h \
           algorithm/Eigen/src/Core/Ref.h \
           algorithm/Eigen/src/Core/Replicate.h \
           algorithm/Eigen/src/Core/Reshaped.h \
           algorithm/Eigen/src/Core/ReturnByValue.h \
           algorithm/Eigen/src/Core/Reverse.h \
           algorithm/Eigen/src/Core/Select.h \
           algorithm/Eigen/src/Core/SelfAdjointView.h \
           algorithm/Eigen/src/Core/SelfCwiseBinaryOp.h \
           algorithm/Eigen/src/Core/Solve.h \
           algorithm/Eigen/src/Core/SolverBase.h \
           algorithm/Eigen/src/Core/SolveTriangular.h \
           algorithm/Eigen/src/Core/StableNorm.h \
           algorithm/Eigen/src/Core/StlIterators.h \
           algorithm/Eigen/src/Core/Stride.h \
           algorithm/Eigen/src/Core/Swap.h \
           algorithm/Eigen/src/Core/Transpose.h \
           algorithm/Eigen/src/Core/Transpositions.h \
           algorithm/Eigen/src/Core/TriangularMatrix.h \
           algorithm/Eigen/src/Core/VectorBlock.h \
           algorithm/Eigen/src/Core/VectorwiseOp.h \
           algorithm/Eigen/src/Core/Visitor.h \
           algorithm/Eigen/src/Eigenvalues/ComplexEigenSolver.h \
           algorithm/Eigen/src/Eigenvalues/ComplexSchur.h \
           algorithm/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \
           algorithm/Eigen/src/Eigenvalues/EigenSolver.h \
           algorithm/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \
           algorithm/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \
           algorithm/Eigen/src/Eigenvalues/HessenbergDecomposition.h \
           algorithm/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \
           algorithm/Eigen/src/Eigenvalues/RealQZ.h \
           algorithm/Eigen/src/Eigenvalues/RealSchur.h \
           algorithm/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \
           algorithm/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \
           algorithm/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \
           algorithm/Eigen/src/Eigenvalues/Tridiagonalization.h \
           algorithm/Eigen/src/Geometry/AlignedBox.h \
           algorithm/Eigen/src/Geometry/AngleAxis.h \
           algorithm/Eigen/src/Geometry/EulerAngles.h \
           algorithm/Eigen/src/Geometry/Homogeneous.h \
           algorithm/Eigen/src/Geometry/Hyperplane.h \
           algorithm/Eigen/src/Geometry/OrthoMethods.h \
           algorithm/Eigen/src/Geometry/ParametrizedLine.h \
           algorithm/Eigen/src/Geometry/Quaternion.h \
           algorithm/Eigen/src/Geometry/Rotation2D.h \
           algorithm/Eigen/src/Geometry/RotationBase.h \
           algorithm/Eigen/src/Geometry/Scaling.h \
           algorithm/Eigen/src/Geometry/Transform.h \
           algorithm/Eigen/src/Geometry/Translation.h \
           algorithm/Eigen/src/Geometry/Umeyama.h \
           algorithm/Eigen/src/Householder/BlockHouseholder.h \
           algorithm/Eigen/src/Householder/Householder.h \
           algorithm/Eigen/src/Householder/HouseholderSequence.h \
           algorithm/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \
           algorithm/Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \
           algorithm/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \
           algorithm/Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h \
           algorithm/Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \
           algorithm/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \
           algorithm/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h \
           algorithm/Eigen/src/IterativeLinearSolvers/SolveWithGuess.h \
           algorithm/Eigen/src/Jacobi/Jacobi.h \
           algorithm/Eigen/src/KLUSupport/KLUSupport.h \
           algorithm/Eigen/src/LU/Determinant.h \
           algorithm/Eigen/src/LU/FullPivLU.h \
           algorithm/Eigen/src/LU/InverseImpl.h \
           algorithm/Eigen/src/LU/PartialPivLU.h \
           algorithm/Eigen/src/LU/PartialPivLU_LAPACKE.h \
           algorithm/Eigen/src/MetisSupport/MetisSupport.h \
           algorithm/Eigen/src/misc/blas.h \
           algorithm/Eigen/src/misc/Image.h \
           algorithm/Eigen/src/misc/Kernel.h \
           algorithm/Eigen/src/misc/lapack.h \
           algorithm/Eigen/src/misc/lapacke.h \
           algorithm/Eigen/src/misc/lapacke_mangling.h \
           algorithm/Eigen/src/misc/RealSvd2x2.h \
           algorithm/Eigen/src/OrderingMethods/Amd.h \
           algorithm/Eigen/src/OrderingMethods/Eigen_Colamd.h \
           algorithm/Eigen/src/OrderingMethods/Ordering.h \
           algorithm/Eigen/src/PardisoSupport/PardisoSupport.h \
           algorithm/Eigen/src/PaStiXSupport/PaStiXSupport.h \
           algorithm/Eigen/src/plugins/ArrayCwiseBinaryOps.h \
           algorithm/Eigen/src/plugins/ArrayCwiseUnaryOps.h \
           algorithm/Eigen/src/plugins/BlockMethods.h \
           algorithm/Eigen/src/plugins/CommonCwiseBinaryOps.h \
           algorithm/Eigen/src/plugins/CommonCwiseUnaryOps.h \
           algorithm/Eigen/src/plugins/IndexedViewMethods.h \
           algorithm/Eigen/src/plugins/MatrixCwiseBinaryOps.h \
           algorithm/Eigen/src/plugins/MatrixCwiseUnaryOps.h \
           algorithm/Eigen/src/plugins/ReshapedMethods.h \
           algorithm/Eigen/src/QR/ColPivHouseholderQR.h \
           algorithm/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \
           algorithm/Eigen/src/QR/CompleteOrthogonalDecomposition.h \
           algorithm/Eigen/src/QR/FullPivHouseholderQR.h \
           algorithm/Eigen/src/QR/HouseholderQR.h \
           algorithm/Eigen/src/QR/HouseholderQR_LAPACKE.h \
           algorithm/Eigen/src/SparseCholesky/SimplicialCholesky.h \
           algorithm/Eigen/src/SparseCholesky/SimplicialCholesky_impl.h \
           algorithm/Eigen/src/SparseCore/AmbiVector.h \
           algorithm/Eigen/src/SparseCore/CompressedStorage.h \
           algorithm/Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \
           algorithm/Eigen/src/SparseCore/MappedSparseMatrix.h \
           algorithm/Eigen/src/SparseCore/SparseAssign.h \
           algorithm/Eigen/src/SparseCore/SparseBlock.h \
           algorithm/Eigen/src/SparseCore/SparseColEtree.h \
           algorithm/Eigen/src/SparseCore/SparseCompressedBase.h \
           algorithm/Eigen/src/SparseCore/SparseCwiseBinaryOp.h \
           algorithm/Eigen/src/SparseCore/SparseCwiseUnaryOp.h \
           algorithm/Eigen/src/SparseCore/SparseDenseProduct.h \
           algorithm/Eigen/src/SparseCore/SparseDiagonalProduct.h \
           algorithm/Eigen/src/SparseCore/SparseDot.h \
           algorithm/Eigen/src/SparseCore/SparseFuzzy.h \
           algorithm/Eigen/src/SparseCore/SparseMap.h \
           algorithm/Eigen/src/SparseCore/SparseMatrix.h \
           algorithm/Eigen/src/SparseCore/SparseMatrixBase.h \
           algorithm/Eigen/src/SparseCore/SparsePermutation.h \
           algorithm/Eigen/src/SparseCore/SparseProduct.h \
           algorithm/Eigen/src/SparseCore/SparseRedux.h \
           algorithm/Eigen/src/SparseCore/SparseRef.h \
           algorithm/Eigen/src/SparseCore/SparseSelfAdjointView.h \
           algorithm/Eigen/src/SparseCore/SparseSolverBase.h \
           algorithm/Eigen/src/SparseCore/SparseSparseProductWithPruning.h \
           algorithm/Eigen/src/SparseCore/SparseTranspose.h \
           algorithm/Eigen/src/SparseCore/SparseTriangularView.h \
           algorithm/Eigen/src/SparseCore/SparseUtil.h \
           algorithm/Eigen/src/SparseCore/SparseVector.h \
           algorithm/Eigen/src/SparseCore/SparseView.h \
           algorithm/Eigen/src/SparseCore/TriangularSolver.h \
           algorithm/Eigen/src/SparseLU/SparseLU.h \
           algorithm/Eigen/src/SparseLU/SparseLU_column_bmod.h \
           algorithm/Eigen/src/SparseLU/SparseLU_column_dfs.h \
           algorithm/Eigen/src/SparseLU/SparseLU_copy_to_ucol.h \
           algorithm/Eigen/src/SparseLU/SparseLU_gemm_kernel.h \
           algorithm/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h \
           algorithm/Eigen/src/SparseLU/SparseLU_kernel_bmod.h \
           algorithm/Eigen/src/SparseLU/SparseLU_Memory.h \
           algorithm/Eigen/src/SparseLU/SparseLU_panel_bmod.h \
           algorithm/Eigen/src/SparseLU/SparseLU_panel_dfs.h \
           algorithm/Eigen/src/SparseLU/SparseLU_pivotL.h \
           algorithm/Eigen/src/SparseLU/SparseLU_pruneL.h \
           algorithm/Eigen/src/SparseLU/SparseLU_relax_snode.h \
           algorithm/Eigen/src/SparseLU/SparseLU_Structs.h \
           algorithm/Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h \
           algorithm/Eigen/src/SparseLU/SparseLU_Utils.h \
           algorithm/Eigen/src/SparseLU/SparseLUImpl.h \
           algorithm/Eigen/src/SparseQR/SparseQR.h \
           algorithm/Eigen/src/SPQRSupport/SuiteSparseQRSupport.h \
           algorithm/Eigen/src/StlSupport/details.h \
           algorithm/Eigen/src/StlSupport/StdDeque.h \
           algorithm/Eigen/src/StlSupport/StdList.h \
           algorithm/Eigen/src/StlSupport/StdVector.h \
           algorithm/Eigen/src/SuperLUSupport/SuperLUSupport.h \
           algorithm/Eigen/src/SVD/BDCSVD.h \
           algorithm/Eigen/src/SVD/JacobiSVD.h \
           algorithm/Eigen/src/SVD/JacobiSVD_LAPACKE.h \
           algorithm/Eigen/src/SVD/SVDBase.h \
           algorithm/Eigen/src/SVD/UpperBidiagonalization.h \
           algorithm/Eigen/src/UmfPackSupport/UmfPackSupport.h \
           algorithm/Eigen/src/Core/functors/AssignmentFunctors.h \
           algorithm/Eigen/src/Core/functors/BinaryFunctors.h \
           algorithm/Eigen/src/Core/functors/NullaryFunctors.h \
           algorithm/Eigen/src/Core/functors/StlFunctors.h \
           algorithm/Eigen/src/Core/functors/TernaryFunctors.h \
           algorithm/Eigen/src/Core/functors/UnaryFunctors.h \
           algorithm/Eigen/src/Core/products/GeneralBlockPanelKernel.h \
           algorithm/Eigen/src/Core/products/GeneralMatrixMatrix.h \
           algorithm/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \
           algorithm/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \
           algorithm/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \
           algorithm/Eigen/src/Core/products/GeneralMatrixVector.h \
           algorithm/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \
           algorithm/Eigen/src/Core/products/Parallelizer.h \
           algorithm/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \
           algorithm/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \
           algorithm/Eigen/src/Core/products/SelfadjointMatrixVector.h \
           algorithm/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \
           algorithm/Eigen/src/Core/products/SelfadjointProduct.h \
           algorithm/Eigen/src/Core/products/SelfadjointRank2Update.h \
           algorithm/Eigen/src/Core/products/TriangularMatrixMatrix.h \
           algorithm/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \
           algorithm/Eigen/src/Core/products/TriangularMatrixVector.h \
           algorithm/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \
           algorithm/Eigen/src/Core/products/TriangularSolverMatrix.h \
           algorithm/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \
           algorithm/Eigen/src/Core/products/TriangularSolverVector.h \
           algorithm/Eigen/src/Core/util/BlasUtil.h \
           algorithm/Eigen/src/Core/util/ConfigureVectorization.h \
           algorithm/Eigen/src/Core/util/Constants.h \
           algorithm/Eigen/src/Core/util/DisableStupidWarnings.h \
           algorithm/Eigen/src/Core/util/ForwardDeclarations.h \
           algorithm/Eigen/src/Core/util/IndexedViewHelper.h \
           algorithm/Eigen/src/Core/util/IntegralConstant.h \
           algorithm/Eigen/src/Core/util/Macros.h \
           algorithm/Eigen/src/Core/util/Memory.h \
           algorithm/Eigen/src/Core/util/Meta.h \
           algorithm/Eigen/src/Core/util/MKL_support.h \
           algorithm/Eigen/src/Core/util/NonMPL2.h \
           algorithm/Eigen/src/Core/util/ReenableStupidWarnings.h \
           algorithm/Eigen/src/Core/util/ReshapedHelper.h \
           algorithm/Eigen/src/Core/util/StaticAssert.h \
           algorithm/Eigen/src/Core/util/SymbolicIndex.h \
           algorithm/Eigen/src/Core/util/XprHelper.h \
           algorithm/Eigen/src/Geometry/arch/Geometry_SIMD.h \
           algorithm/Eigen/src/Geometry/arch/Geometry_SSE.h \
           algorithm/Eigen/src/LU/arch/Inverse_SSE.h \
           algorithm/Eigen/src/LU/arch/InverseSize4.h \
           algorithm/Eigen/src/Core/arch/AltiVec/Complex.h \
           algorithm/Eigen/src/Core/arch/AltiVec/MathFunctions.h \
           algorithm/Eigen/src/Core/arch/AltiVec/MatrixProduct.h \
           algorithm/Eigen/src/Core/arch/AltiVec/MatrixProductCommon.h \
           algorithm/Eigen/src/Core/arch/AltiVec/MatrixProductMMA.h \
           algorithm/Eigen/src/Core/arch/AltiVec/PacketMath.h \
           algorithm/Eigen/src/Core/arch/AVX/Complex.h \
           algorithm/Eigen/src/Core/arch/AVX/MathFunctions.h \
           algorithm/Eigen/src/Core/arch/AVX/PacketMath.h \
           algorithm/Eigen/src/Core/arch/AVX/TypeCasting.h \
           algorithm/Eigen/src/Core/arch/AVX512/Complex.h \
           algorithm/Eigen/src/Core/arch/AVX512/MathFunctions.h \
           algorithm/Eigen/src/Core/arch/AVX512/PacketMath.h \
           algorithm/Eigen/src/Core/arch/AVX512/TypeCasting.h \
           algorithm/Eigen/src/Core/arch/CUDA/Complex.h \
           algorithm/Eigen/src/Core/arch/Default/BFloat16.h \
           algorithm/Eigen/src/Core/arch/Default/ConjHelper.h \
           algorithm/Eigen/src/Core/arch/Default/GenericPacketMathFunctions.h \
           algorithm/Eigen/src/Core/arch/Default/GenericPacketMathFunctionsFwd.h \
           algorithm/Eigen/src/Core/arch/Default/Half.h \
           algorithm/Eigen/src/Core/arch/Default/Settings.h \
           algorithm/Eigen/src/Core/arch/Default/TypeCasting.h \
           algorithm/Eigen/src/Core/arch/GPU/MathFunctions.h \
           algorithm/Eigen/src/Core/arch/GPU/PacketMath.h \
           algorithm/Eigen/src/Core/arch/GPU/TypeCasting.h \
           algorithm/Eigen/src/Core/arch/MSA/Complex.h \
           algorithm/Eigen/src/Core/arch/MSA/MathFunctions.h \
           algorithm/Eigen/src/Core/arch/MSA/PacketMath.h \
           algorithm/Eigen/src/Core/arch/NEON/Complex.h \
           algorithm/Eigen/src/Core/arch/NEON/GeneralBlockPanelKernel.h \
           algorithm/Eigen/src/Core/arch/NEON/MathFunctions.h \
           algorithm/Eigen/src/Core/arch/NEON/PacketMath.h \
           algorithm/Eigen/src/Core/arch/NEON/TypeCasting.h \
           algorithm/Eigen/src/Core/arch/SSE/Complex.h \
           algorithm/Eigen/src/Core/arch/SSE/MathFunctions.h \
           algorithm/Eigen/src/Core/arch/SSE/PacketMath.h \
           algorithm/Eigen/src/Core/arch/SSE/TypeCasting.h \
           algorithm/Eigen/src/Core/arch/SVE/MathFunctions.h \
           algorithm/Eigen/src/Core/arch/SVE/PacketMath.h \
           algorithm/Eigen/src/Core/arch/SVE/TypeCasting.h \
           algorithm/Eigen/src/Core/arch/SYCL/InteropHeaders.h \
           algorithm/Eigen/src/Core/arch/SYCL/MathFunctions.h \
           algorithm/Eigen/src/Core/arch/SYCL/PacketMath.h \
           algorithm/Eigen/src/Core/arch/SYCL/SyclMemoryModel.h \
           algorithm/Eigen/src/Core/arch/SYCL/TypeCasting.h \
           algorithm/Eigen/src/Core/arch/ZVector/Complex.h \
           algorithm/Eigen/src/Core/arch/ZVector/MathFunctions.h \
           algorithm/Eigen/src/Core/arch/ZVector/PacketMath.h \
           algorithm/Eigen/src/Core/arch/HIP/hcc/math_constants.h
SOURCES += main.cpp \
           algorithm/MeshTransfer.cpp \
           algorithm/Renderable/bmesh.cpp \
           algorithm/Renderable/ObjMesh.cpp
